services:
  # 1. Aplicação Node.js
  app:
    build: ./
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mosquitto

  # 2. Broker MQTT Mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 3. Banco de Dados MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: